### ISSUE TITLE
Add Data Manually function has an error - not working

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Faith-Trends#1]

**Comment by debajyotiGuha** [comment]
Resolved.
Please logged in http://cleonix.biz/faithtrends/login here. And changed are visible here.

**Comment by bikash02** [comment]
@camerontrimble Please check.Resolved the issue.

**Comment by debdiproy** [comment]
@rikalively. Check this has been resolved

**Comment by rikalively** [comment]
I'm getting a blank screen after I try to add data manually.
<img width="1175" alt="screen shot 2016-12-12 at 3 12 55 pm" src="https://cloud.githubusercontent.com/assets/23104131/21115044/7d7ce1e4-c07d-11e6-8fed-64fade80efd6.png">

**Comment by debajyotiGuha** [comment]
This problem occurred cause, I'm working in rating type question. Once that complete this problem will be resolved.  Except rating type question, this is working for others. please check once ad give feedback.

**Comment by debdiproy** [comment]
@rikalively Please check the update.

**Comment by rikalively** [comment]
Working. Thank you!
