### ISSUE TITLE
Cannot add new organization

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#11]
I've tried filling out the form but it will not show up on the organization list.

**Comment by bikash02** [comment]
Can you please send me the url that you were trying to access?

**Comment by rikalively** [comment]
http://cleonix.biz/faithtrends/organizations

**Comment by bikash02** [comment]
We are working on the organization module so that every user add their own organization.You have to allow us for this week for updating the system.
Please check  #3

**Comment by rikalively** [comment]
thank you

**Comment by rikalively** [comment]
How is the update coming? I still cannot add new organizations.

**Comment by Designer-cleonix** [comment]
@bikash02 what is the progress? please update.

**Comment by debajyotiGuha** [comment]
Now the structure has changed. Please check once and give your feedback.

**Comment by rikalively** [comment]
Working now. Thank you!
