### ISSUE TITLE
It looks like the notes are not isolating to one account. 

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Faith-Trends#14]
I am logged in as Dawn Hammond. But I can see Amy Olrick's note in the system. Amy and Dawn should never see each others info. 

![screen shot 2016-11-04 at 11 24 50 am](https://cloud.githubusercontent.com/assets/15096099/20011290/755ad8c8-a281-11e6-8362-a64bd20833c4.png)

**Comment by debajyotiGuha** [comment]
This is not a note section. This is a message section. Someone can send a message to other. That's why the receiver can read the message.

**Comment by bikash02** [comment]
@camerontrimble @debdiproy Can you please tell me what will be the scope of the module.Is it just like a note section where user can save their personal note into the system and only they can view it when logged into the system?No one will view the message/notes even they are in same organization.
Please confirm us and I will update the system accordingly.

**Comment by debajyotiGuha** [comment]
The message section changed to a note section. Please check once.
