### ISSUE TITLE
http://cleonix.biz/faithtrends/dashboard#readNote not working

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Faith-Trends#15]

**Comment by debajyotiGuha** [comment]
Read message is working in the provided link. Screen shot added with this. Please check once and give feedback.
![screenshot from 2016-11-07 17 55 12](https://cloud.githubusercontent.com/assets/18532725/20057778/835d24a0-a513-11e6-9fca-083c1c341596.png)

**Comment by debdiproy** [comment]
@rikalively. This is working and updated.

**Comment by rikalively** [comment]
I'm not quite sure what the initial problem was in the first place. I'm assuming the message widget on the dashboard is like a notes widget? I am unable to send any messages from my dashboard to test. 
<img width="1175" alt="screen shot 2016-12-12 at 3 23 30 pm" src="https://cloud.githubusercontent.com/assets/23104131/21115432/3ec21d96-c07f-11e6-87eb-c5b316a8c9f8.png">

The "Send new message" on this screen does not work.

**Comment by bikash02** [comment]
@debajyotiGuha Please resolve the issue

**Comment by debajyotiGuha** [comment]
Resolved. Please check once.

**Comment by rikalively** [comment]
<img width="1179" alt="screen shot 2016-12-15 at 10 13 38 am" src="https://cloud.githubusercontent.com/assets/23104131/21229308/335209b2-c2af-11e6-9476-53a19558ec58.png">

The message button is gone completely from my menu

**Comment by debajyotiGuha** [comment]
As @bikash02 sir told me I replaced the message section with a note section. That's why I removed the message icon.

**Comment by bikash02** [comment]
@rikalively Please check the issue #14 
You were requesting for the note module.So we have removed the message and make it as notes module.Now the notes are isolating to one account.

Please let me know what you want to do with this section?Waiting for your reply.

**Comment by rikalively** [comment]
Okay, I see that Cameron requested that.
I was able to post a note but I cannot delete it when I want to write something different. 
<img width="347" alt="screen shot 2016-12-16 at 8 47 55 am" src="https://cloud.githubusercontent.com/assets/23104131/21264861/89cdb7e2-c36c-11e6-87ec-6c117f102413.png">

**Comment by debajyotiGuha** [comment]
Updated. Please check once.

**Comment by rikalively** [comment]
Thank you!!
