### ISSUE TITLE
Format email

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Faith-Trends#16]
Different font sizes and doesn't fit on the screen, regardless of the screen size

![screen shot 2016-11-04 at 11 54 13 am](https://cloud.githubusercontent.com/assets/15096099/20012415/76b1ba30-a285-11e6-86af-42350cfedff4.png)

**Comment by bikash02** [comment]
@Designer-cleonix @i-puspita @debajyotiGuha Please check the design and resolve it asap.

**Comment by i-puspita** [comment]
Working on it. Updated by tomorrow

**Comment by i-puspita** [comment]
updated. Please Check.
