### ISSUE TITLE
Description field should not be limited by number of characters

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Faith-Trends#17]
![screen shot 2016-11-04 at 12 50 24 pm](https://cloud.githubusercontent.com/assets/15096099/20014444/5ed57fd4-a28d-11e6-801c-4e12cad3a806.png)

**Comment by debajyotiGuha** [comment]
I have checked, but unable to find the place where description field has character limit. Please add the link of the page or specify the field with page name and field name.

**Comment by camerontrimble** [comment]
Test by writing a bunch of text in the box. You can also see the issue here: https://vimeo.com/190763692

**Comment by debajyotiGuha** [comment]
Now I got it. It will changed before end of today.

**Comment by debajyotiGuha** [comment]
Updated. Please check once.

**Comment by bikash02** [comment]
@camerontrimble We have updated the code.Please check once again.

**Comment by amyolrick** [comment]
Great, thank you.
