### ISSUE TITLE
We need a "rating" question

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Faith-Trends#18]
For Example: On a scale of 1 to 10, how would you rank the importance of...?"

**Comment by debajyotiGuha** [comment]
Working on user and organization module. Once that completed, can be able to work on this.

**Comment by bikash02** [comment]
@debajyotiGuha have you completed the module?

**Comment by debajyotiGuha** [comment]
I have completed the organization module. But there are few problems on survey settings page. On which @debdiproy  sir working now. Once he complete his section I will complete the above point.

**Comment by debajyotiGuha** [comment]
Start working on this. Will be updated by tomorrow.

**Comment by debdiproy** [comment]
@debajyotiGuha . I believe all the problems of the survey settings page has been resolved now. So complete this fastest and update us on this.

**Comment by debajyotiGuha** [comment]
Rating type question added. Rating range and steps can be added in the time of numeric question addition.
And that range will shown in answer page with that range and steps.
