### ISSUE TITLE
Issues adding multiple emails for survey

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#19]
On the track trends form, every time I click "Add email" it deletes the ones I already typed in. 
It should save the ones I already typed in when I click "Add email."
<img width="600" alt="screen shot 2016-11-07 at 11 37 54 am" src="https://cloud.githubusercontent.com/assets/23104131/20066163/a480ba78-a4de-11e6-8a85-6d202df4217d.png">

**Comment by bikash02** [comment]
@debajyotiGuha replace the function with ajax.

**Comment by debajyotiGuha** [comment]
Working on this.

**Comment by debajyotiGuha** [comment]
Updated. Please check.

**Comment by rikalively** [comment]
Looks great. Thank you!!
