### ISSUE TITLE
Cannot assign user to a survey

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#20]
I tried to assign my other account to a survey and I currently have no access to the surveys. My survey ladder and surveys dashboard are both empty.

**Comment by debajyotiGuha** [comment]
This feature required changes in user and organization module, on which I'm already working. Once that completed it will be started.

**Comment by rikalively** [comment]
thank you!

**Comment by debajyotiGuha** [comment]
Now it's working. Please check once.

**Comment by rikalively** [comment]
Working now. Thank you!
