### ISSUE TITLE
Calendar does not save correct times

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#21]
The calendar widget is saving the wrong times for the appointments I create. I typed in 11:00am - 12:30pm. Also, there needs to be more options for creating the time of events. If I need to remember an appointment at 1:45pm I only have the options for 1:00 or 1:30. 

<img width="876" alt="screen shot 2016-11-07 at 11 47 05 am" src="https://cloud.githubusercontent.com/assets/23104131/20066572/fc6d241e-a4df-11e6-957a-10d6c435d4ea.png">

**Comment by bikash02** [comment]
@camerontrimble @debdiproy The calender is not configured in the system.It's a static data.
If you want to save event data & sync to the calendar then we have to configure .Please let me know if you make it dynamic.

**Comment by camerontrimble** [comment]
This isn't a critical feature. We could remove this entirely. @rikalively we should think about what information we do want to put on the dashboard. We can design it in any way we want...and what we currently have is not particularly strategic.

**Comment by rikalively** [comment]
@camerontrimble Okay - will keep that in mind! I'll discuss with @amyolrick
