### ISSUE TITLE
Cannot remove user profile picture

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#22]
People may want to remove their profile picture after a while. Can we add an option to remove pictures after uploading?

**Comment by debajyotiGuha** [comment]
Need to talk with @bikash02 sir.

**Comment by bikash02** [comment]
@debajyotiGuha Please add the remove icon and once the user removed their profile picture set a placeholder image.

**Comment by debajyotiGuha** [comment]
Updated.

**Comment by rikalively** [comment]
Thank you!
