### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#25]
I just tried to login from two different accounts and I am not able to get in. I am unable to follow up on any previous issues since I cannot get into the system.

**Comment by debajyotiGuha** [comment]
Once you register please a auto generated mail will be sent to your registered email id. A account activation link will be there in that mail. And login can be possible only after activate the account by click on the link. Please try the process for one more time and give feedback.

**Comment by rikalively** [comment]
I was able to create a new account. What happened to the old accounts? Did I lose the surveys I created on those accounts?

**Comment by amyolrick** [comment]
I am also unable to log into my account and am unable to use the forgotten password link to log back into my account. Please fix this asap. After both of these issues are fixed, I would appreciate it if someone would call me via Skype to explain to me why this happened and exactly what steps have been put in place to make sure that something like this does not happen again.

**Comment by Designer-cleonix** [comment]
Look into this urgently @bikash02 @debajyotiGuha

**Comment by debajyotiGuha** [comment]
Cause the whole db structure has changed, @bikash02  sir truncate the old db tables. Please start fresh testing from now. 
If the previous data will be there, then that can conflict the current structure and data. So remove previous data was the only solution to this problem.

**Comment by bikash02** [comment]
@amyolrick @rikalively @camerontrimble  we were restructuring the system and updated the module like users,survey and organization.If I didn't  truncate the previous data then it might be conflicted with old and new datas.So please try to understand the situation and We are very sorry for that.

If you are still not able to logged in into the system please let me know we'll definitely help you.
