### ISSUE TITLE
Cannot delete survey questions

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#26]
When creating or editing a survey, you cannot delete different portions of it. So if I made a mistake and I want to remove one of the questions, I cannot do that without deleting the whole survey.

<img width="1138" alt="screen shot 2016-11-21 at 10 50 00 am" src="https://cloud.githubusercontent.com/assets/23104131/20489351/4484b5ac-afd8-11e6-9f53-e6c37ca44948.png">

**Comment by debajyotiGuha** [comment]
There are few similar kind of problems on this page. @debdiproy sir working on this point. We will update soon on this.

**Comment by rikalively** [comment]
How are we doing on this issue?

**Comment by debdiproy** [comment]
@rikalively I have been working on this one for a bit of time as there are a few other JQuery clash thats stopped me from resolving this, however I am very close and will be positively resolved before Wednesday.

**Comment by rikalively** [comment]
Thank you so much for all of your hard work!

**Comment by debdiproy** [comment]
Hello @rikalively @debajyotiGuha I have resolved the issue of the checkboxes so now you can click the checkboxes of Multiple choice question.

**Comment by debajyotiGuha** [comment]
Updated. Please check once.

**Comment by rikalively** [comment]
I see that you can delete portions of the multiple choice question - thank you.
But I am still unable to delete questions from the survey. Users should have the option to delete a whole question. For example, if they change their mind and would rather use a numeric question rather than a descriptive question - you have to delete all of your progress rather than just deleting one survey question.

**Comment by debdiproy** [comment]
@debajyotiGuha @bikash02 @Designer-cleonix   Add a delete option to each question so that the question can be deleted from the survey.

**Comment by debajyotiGuha** [comment]
There is already a archive option. With which any question can be archived. But if a delete button required, then please comment and I will add that option.

**Comment by debdiproy** [comment]
@rikalively  Please use the archive (Yes/No) to delete a question. Updated

**Comment by rikalively** [comment]
Archiving isn't deleting the question on my end. And I don't think users would know that archiving a question would be the same as deleting it. If we archive them would that be the same as saving them for a later date? 
We should keep that feature but we should also have the option to delete a question in case someone made a typo or decided they didn't want to use that question.

**Comment by debdiproy** [comment]
@rikalively I understood your point and will implement it accordingly and show you by tomorrow.

**Comment by debajyotiGuha** [comment]
Individual delete button for every question added. Please check once.

**Comment by rikalively** [comment]
Great! Thanks so much!
