### ISSUE TITLE
Client lost survey data

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#27]
@amyolrick and I had a meeting with Dawn Hammond this morning. She has been testing the system as well and told us that she lost all of the survey data she created this morning. 
Do you have an idea of what may have caused this? She doesn't want to re-enter the surveys until she knows that she won't lose them.
Let me know as soon as you know so I can contact her.

**Comment by debajyotiGuha** [comment]
Cause the whole structure has changed, previous data will not fit in this structure. That is the only reason why we remove those data. Please add one more time and check, it will not lost any more.

**Comment by rikalively** [comment]
Did we change the structure yesterday? She had just created two surveys yesterday morning and in a few hours lost her work. 
I was on in the morning as well and did not experience any issues.

**Comment by debajyotiGuha** [comment]
Please try to test from fresh. I don't think problem will occurred any more. If still find data lost issue please inform us. We will definitely fix this.

**Comment by rikalively** [comment]
Okay thank you @debajyotiGuha

**Comment by debdiproy** [comment]
@rikalively . You can close this I think as this will not be a problem next time as @debajyotiGuha said.
