### ISSUE TITLE
Built-in frequency not appearing

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#28]
Our client is adding frequencies but they are not showing up on her frequency page. 
Additionally, when I add a new frequency, I do not see it listed as an option when I go to create a survey.

**Comment by debajyotiGuha** [comment]
If you added those frequencies before db change then that are not present there right now. So please add frequencies one more time and I think it will be appear in the time of adding survey.

**Comment by rikalively** [comment]
I can see them now. Thank you!
