### ISSUE TITLE
Create survey button leads to blank page

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#29]
Here is the page it takes you to when you click on "create survey"
<img width="1151" alt="screen shot 2016-11-21 at 11 09 15 am" src="https://cloud.githubusercontent.com/assets/23104131/20506286/f9c2beda-b020-11e6-8983-a64f715737c7.png">

Instead, it would make more sense for the "Create survey" button to lead you to this page
<img width="1151" alt="screen shot 2016-11-21 at 7 29 45 pm" src="https://cloud.githubusercontent.com/assets/23104131/20506315/21bda2ce-b021-11e6-8c24-9328c02fdaaa.png">

Thank you!

**Comment by debajyotiGuha** [comment]
Issue solved. Please check once.

**Comment by rikalively** [comment]
This looks great!! Thank you
