### ISSUE TITLE
Allow users to create their own organization and survey

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Faith-Trends#3]

**Comment by Designer-cleonix** [comment]
@debajyotiGuha  Where is the update?

**Comment by debajyotiGuha** [comment]
In current structure of this project if any user create a new organization then he will be registered as organization admin and he can be able to add his own surveys as well. In db structure now there is probation to add only one organization with a user. And only one user can be the organization admin.
Hence if user register in other organization then he will be added as a user.
Then he can't able to add his own organization and only admin can add survey.
For this change in structure we have to change the user table structure and organization table structure.
And cause user table and organization table used in all the sections of this project it will take much time to change.

And for this change need to discuss with Debdip sir. And after that only I can give exact time estimation to perform the task.

**Comment by bikash02** [comment]
@camerontrimble @debdiproy I have talked to developer and it will take sometimes to get resolve.We have to update database structure for organization and survey and map into them otherwise its not happen.So please allow us to change the database structure and also the coding or script.
Time needed to get it resolve: 5-6 working days.

Waiting for your opinion both.

**Comment by camerontrimble** [comment]
Do it. We need an easy way for users to be able to subscribe to this software.

**Comment by Designer-cleonix** [comment]
@bikash02 please give an update on this.

**Comment by bikash02** [comment]
Start working on the issue and will get the update before 11th,Nov

**Comment by debajyotiGuha** [comment]
Now the structure has changed. Please check once and give your feedback.

**Comment by bikash02** [comment]
@camerontrimble We have updated the db structure and now you'll able to add your own organization and survey.

**Comment by debdiproy** [comment]
@rikalively. This has been completed. Users can now create their own organization.
