### ISSUE TITLE
Preview survey button confusing

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#30]
Is there a way we can make it easier to go from the "preview survey" page back to the "editing survey" page? When you click "preview survey" it opens a new tab but when you hit the back button on your browser it closes the tab out.
Our client pointed this out and when she's using this feature she ends up with too many tabs.

**Comment by debajyotiGuha** [comment]
Issue solved. Now survey preview open in the same window and back on the previous page by clicking on the back button.

**Comment by rikalively** [comment]
Thank you!
