### ISSUE TITLE
Duplicate surveys in bank

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#31]
When I go to create a new survey, it shows up twice in my survey bank.

<img width="1159" alt="screen shot 2016-11-22 at 9 01 57 am" src="https://cloud.githubusercontent.com/assets/23104131/20526513/6c499cd2-b092-11e6-9a9d-a1ae8ea6d71c.png">

**Comment by debajyotiGuha** [comment]
Issue solved. Please check once.

**Comment by rikalively** [comment]
Great, thank you!
