### ISSUE TITLE
Words not visible for multiple choice question

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#32]
Our we able to have the first few words of the question visible for the multiple-choice question in the same way the other ones are? 
It'll make it easier for users to re-order their survey questions.

<img width="820" alt="screen shot 2016-11-22 at 9 07 12 am" src="https://cloud.githubusercontent.com/assets/23104131/20526679/198093f6-b093-11e6-8f1a-7be806dc661f.png">

**Comment by debajyotiGuha** [comment]
There are few similar kind of problems on this page. @debdiproy sir working on this point. We will update soon on this.
This problem is similar with
https://github.com/ConvergenceUS/Faith-Trends/issues/26
Both will be solved together.

**Comment by debajyotiGuha** [comment]
Resolved. Please check once.

**Comment by rikalively** [comment]
Thank you!
