### ISSUE TITLE
Confusing form for numeric question

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#33]
This form is a little confusing. Maybe the "question title" should be the first box to fill out on the form since it goes above the "question" on the survey. Also what does the subtext do? Whatever text I put in that form does not appear on the actually survey.

<img width="474" alt="screen shot 2016-11-25 at 10 40 22 am" src="https://cloud.githubusercontent.com/assets/23104131/20629848/9d42f020-b2fb-11e6-98cc-47d1128c0915.png">

**Comment by debdiproy** [comment]
@debajyotiGuha Take care of this

**Comment by debajyotiGuha** [comment]
Subtext has removed and Question title has moved above the Question filed.

**Comment by rikalively** [comment]
Looks good. Thank you!
