### ISSUE TITLE
Surveys not assigning to organizations

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#35]
<img width="1047" alt="screen shot 2016-12-12 at 3 16 16 pm" src="https://cloud.githubusercontent.com/assets/23104131/21115477/67ac45ec-c07f-11e6-8a2c-e2e1c24067c4.png">

When I click add new survey under organizations, they do not save to the organization.

**Comment by debdiproy** [comment]
@rikalively I think Rika you should create a level firstly and then a survey, that is the minimum requirement , because every survey needs a level and an organization.

**Comment by rikalively** [comment]
Okay, I don't know if everyone would think to do that first. Can we provide instructions or not include the "Add survey" button until after you create a level. 
I think users might get frustrated after making a few surveys and not having them show up on the survey ladder list.

**Comment by debdiproy** [comment]
@rikalively Sure I will get this sorted

@debajyotiGuha Please follow the instruction to resolve it. The add survey button should not be visible on each organization until at least one level is added.

**Comment by rikalively** [comment]
Thank you so much!

**Comment by debajyotiGuha** [comment]
Updated. Add survey button will be visible only after user added a level.

**Comment by debdiproy** [comment]
@rikalively. Updated, check and confirm

**Comment by rikalively** [comment]
Great! Thank you!
