### ISSUE TITLE
Can't advance from this page if the email address already exists. Won't let me click anywhere

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Faith-Trends#39]
![screen shot 2017-01-02 at 12 58 56 pm](https://cloud.githubusercontent.com/assets/15096099/21593980/602e66b6-d0eb-11e6-9661-f049591a42fe.png)

I tried to click on the "Log In" text, but won't take me anywhere.

**Comment by debajyotiGuha** [comment]
Resolved. Please check once.
