### ISSUE TITLE
Cannot send out survey

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#4]
Hey everyone! My name is Rika and I've been beta-testing the FaithTrends site. I'm excited to be a part of the team - so thanks for having me!

The first issue I've come across is I am unable to send out the survey - The “track trends” form is not working. I’ve tried to send out the survey to a couple of emails and so far I still haven’t seen them in my inbox.

**Comment by bikash02** [comment]
I have tested and received the email from faith trends.Check once again and leave your comment please.Check the spam inbox as well.

![screenshot from 2016-11-03 18_46_36](https://cloud.githubusercontent.com/assets/16361011/19967630/2f1dac76-a1f7-11e6-85bf-dceea3ac9a3e.png)

**Comment by rikalively** [comment]
Got the survey! Thank you!!

**Comment by bikash02** [comment]
Keep me posted if I can help you for anything else.Thank you!
