### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#42]
Inside the survey under Manage Survey, under Settings, about halfway down it says "Filiers Notes"

And inside the survey, under Manage Survey, under Monitors, in the box under "Add Survey Monitor" it says "Select Moniter" - Monitor is misspelled

**Comment by debajyotiGuha** [comment]
Updated. Please check once.

**Comment by rikalively** [comment]
Thank you!
