### ISSUE TITLE
Unable to create new users

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#6]
Unable to create new users - I created myself two different users on FaithTrends and I haven’t received the invitations in my inbox. The users and the emails are showing up on the user page, I just cannot access either accounts to login.

**Comment by bikash02** [comment]
I will give you update within 30minutes

**Comment by bikash02** [comment]
@rikalively Please login into the system using your credentials and try to add new user.The email will go to user's valid email address and once they will click or verify the activation link,the profile will get ready for them.
http://cleonix.biz/faithtrends/login

**Comment by bikash02** [comment]
If the users not activated their profile,you can't access them.One more thing,please check the spam inbox as well.Please keep me update if the email goes to spam.

**Comment by rikalively** [comment]
It worked this time! Wonderful!!

Now I deleted the old users that I tried to create since the accounts were not created. It won't let me recreate those accounts with those emails. Is there a way to change this? 

Thank you so much

**Comment by bikash02** [comment]
If the system allow you to delete the data permanently from the database then you'll be able to use the emails.But now the system don't permit it.

**Note: If you provide me the users email I will make it for you from the database.**

**Comment by bikash02** [comment]
@rikalively I have removed the emails from the system.Please try to add using the same email.

**Comment by rikalively** [comment]
I was able to open the account. Thank you @bikash02
