### ISSUE TITLE
Survey Addressed to User

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#7]
When I received the surveys in my inbox, they were addressed to "user" instead of my first name. 
Are we able to personalize it?

![unnamed](https://cloud.githubusercontent.com/assets/23104131/19974925/8aedfe02-a1c0-11e6-84a4-4ce54776bc82.png)

**Comment by bikash02** [comment]
I have updated the code and now if you put the email say "bikash02@cleonix.com"  and send the survey link to that email id then the user will get the email and address will be "Dear bikash02".
We don't track the first name from an email,so we took before @. Please let me know your feedback.

**Comment by rikalively** [comment]
The update worked - it addressed me by my name. Thank you!

**Comment by bikash02** [comment]
Anything else?
Please close ticket issue is resolved.Thank you!! :)
