### ISSUE TITLE
No confirmation message

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#8]
After taking the survey, there is no confirmation or thank you page - just a blank screen. 

<img width="1440" alt="screen shot 2016-11-03 at 9 54 14 am" src="https://cloud.githubusercontent.com/assets/23104131/19974970/b3dee132-a1c0-11e6-883c-f606cf57dba3.png">

**Comment by bikash02** [comment]
Once you have submitted the survey answer you'll get a notification.Please have a look.
![screenshot-cleonix biz 2016-11-04 13-45-48](https://cloud.githubusercontent.com/assets/16361011/19998871/31d7068a-a295-11e6-8677-393498befb7e.png)

Let us know if you redirect them to a new page name "thank you".

**Comment by bikash02** [comment]
@debajyotiGuha Please update the thank you page as the below link
https://www.surveymonkey.com/survey-thanks/?sm=_2BcY47teWunRy5mHcpw2ldrHAeMCxz8G41zV3zTv5yxVRNzHWIPb8KoB9udwhCILQ2CHhOPIetymvO7wkqGL9CA_3D_3D

**Comment by debajyotiGuha** [comment]
It will be updated by today.

**Comment by rikalively** [comment]
I just retook the survey and got the same blank page. I will check again after you work on the new update.

**Comment by debajyotiGuha** [comment]
It's resolved. Please check once.

**Comment by rikalively** [comment]
Still cannot get anything.

<img width="1406" alt="screen shot 2016-11-04 at 10 54 39 am" src="https://cloud.githubusercontent.com/assets/23104131/20010054/232d1a38-a27d-11e6-831c-780fbe0a667f.png">

**Comment by bikash02** [comment]
Can you please please retest?
It's working for me.I have tested.

![screenshot-cleonix biz 2016-11-04 20-50-49](https://cloud.githubusercontent.com/assets/16361011/20011873/138c7f14-a2d3-11e6-99d3-499423cf4f64.png)

**Comment by bikash02** [comment]
If you are still getting the blank page,please provide me the page url.I will test myself and It will be more easier to me resolve the issue.Thank you for your quick response !!

**Comment by rikalively** [comment]
here's the blank page - http://cleonix.biz/faithtrends/survey-answer?id=23

here's the actually survey - http://cleonix.biz/faithtrends/survey-answer?id=23

Thank you!

**Comment by bikash02** [comment]
You are getting the blank page because maybe the survey was created by user not the admin.We are working on the users,organization & survey module altering the DB structure and will update you within this week.

**Comment by rikalively** [comment]
okay thank you so much!!

**Comment by rikalively** [comment]
got it working now
