### ISSUE TITLE
Custom email text does not update

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#9]
On the survey settings form, there is a feature to edit the email text. The custom text will show up on the preview email but does not actually save or update once the survey has been sent out. I got the default email text in my inbox.

**Comment by bikash02** [comment]
We have updated the code.Please check once again.Working now!!

**Comment by amyolrick** [comment]
Hello, thank you for working on this. I am looking at the email issue now. In the preview console I see that one paragraph of the email updates, but I cannot edit the whole thing:

![screen shot 2016-11-04 at 9 43 21 am](https://cloud.githubusercontent.com/assets/22732566/20007551/291b9b90-a273-11e6-81c4-85c022e2dae1.png)

And now the email that user receives seems to simply have a blank paragraph if that text was edited:

![screen shot 2016-11-04 at 9 41 54 am](https://cloud.githubusercontent.com/assets/22732566/20007531/16108f7e-a273-11e6-84d3-7375450abcd1.png)

**Comment by camerontrimble** [comment]
Issue with handling '

![screen shot 2016-11-04 at 11 31 09 am](https://cloud.githubusercontent.com/assets/15096099/20011498/3b341c30-a282-11e6-9ee0-725c2b888d81.png)

**Comment by debajyotiGuha** [comment]
Updated this mail. Please check once.

**Comment by bikash02** [comment]
Updated the \' issue as well.Please check once again.

**Comment by debdiproy** [comment]
@rikalively. This has been updated.
